"""Added foreign key

Revision ID: d4d285b83d53
Revises: 67cddd8ef77a
Create Date: 2023-04-03 14:38:48.143798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4d285b83d53'
down_revision = '67cddd8ef77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commenter_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('comments_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('comments_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['commenter_id'], ['id'])
        batch_op.drop_column('post_id')
        batch_op.drop_column('poster_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_ibfk_1', 'posts', ['post_id'], ['id'])
        batch_op.create_foreign_key('comments_ibfk_2', 'users', ['poster_id'], ['id'])
        batch_op.drop_column('commenter_id')

    # ### end Alembic commands ###
